package namedpipecodegen

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

// This function is used by the namedpipe plugin to generate the client-side namedpipe service
func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_NamedPipeClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages(
		"encoding/json", "context", "fmt", "errors", "os", "sync", "time", "github.com/blueprint-uservices/blueprint/runtime/plugins/namedpipe",
	)

	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("NamedPipeClient", clientTemplate, client, outputFile)
}

// Arguments to the template code
type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Imports *gogen.Imports
}

var clientTemplate = `// Blueprint: Auto-generated by the Named Pipe Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	ArgsEncoder *json.Encoder
	ResultDecoder *json.Decoder
	Mutex sync.Mutex
}

func New_{{.Name}}(ctx context.Context, addr string) (*{{.Name}}, error) {
	var err error

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		dir := namedpipe.GetTmpDir("{{.Service.Name}}")
		ticker := time.NewTicker(1 * time.Second)

		// check if directory exists
		for range ticker.C {
			if _, err := os.Stat(dir); os.IsNotExist(err) {
				fmt.Println(dir, "does not exist: server {{.Service.Name}} not ready yet. Retry in 1 second.")
			} else if err == nil {
				ticker.Stop()
				fmt.Println("Server {{.Service.Name}} is ready.")
				wg.Done()
				return
			}
		}
	}()
	wg.Wait()


	// create the pipes. The suffix needs to be unique for each client, so simply using "{{.Service.Name}}" cannot work.
	// Choosing a random string does the job, although it would be ideal to choose the name of the service that is
	// using this client stub
	clientUniqueSuffix := namedpipe.GenerateRandomPipeName() // from the runtime package for namedpipe
	argsPipeName := namedpipe.GetArgsPipeName("{{.Service.Name}}", clientUniqueSuffix)
	resultPipeName := namedpipe.GetResultPipeName("{{.Service.Name}}", clientUniqueSuffix)

	err = namedpipe.CreatePipe(argsPipeName) 
	if err != nil {
		return nil, err
	}
	err = namedpipe.CreatePipe(resultPipeName)
	if err != nil {
		return nil, err
	}

	fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Pipes to service {{.Service.Name}} have been created with unique suffix %s\n", clientUniqueSuffix)

	fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Client %s is opening args pipe %s as write...\n", clientUniqueSuffix, argsPipeName);
	// open the pipes, in this order (the server will also open them in this order)
	argsPipe, err := namedpipe.OpenWritePipe(argsPipeName)
	if err != nil {
		return nil, err
	}
	fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Client %s is opening result pipe %s as read...\n", clientUniqueSuffix, resultPipeName);
	resultPipe, err := namedpipe.OpenReadPipe(resultPipeName)
	if err != nil {
		return nil, err
	}

	fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Pipes to service {{.Service.Name}} have been opened")

	c := &{{.Name}}{}
	c.ArgsEncoder = json.NewEncoder(argsPipe)
	c.ResultDecoder = json.NewDecoder(resultPipe)
	return c, nil
}


{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{SignatureWithRetVars $f}} {

	// Define struct for the arguments. Capitalize the field name with Title to ensure the field
	// is marshalled
	args := struct {
		{{range $i, $arg := $f.Arguments}}
		{{Title $arg.Name}} {{NameOf $arg.Type}}
		{{end}}
	}{}

	// Assign all the struct fields
	{{range $_, $arg := $f.Arguments}}
	args.{{Title $arg.Name}} = {{$arg.Name}}
	{{end}}

	// Marshal the arguments
	bytes_args, err := json.Marshal(args)
	if err != nil {
		return
	}
	
	invocation := namedpipe.Invocation{
		Method: "{{.Name}}",
		Args: bytes_args,
	}

	var response namedpipe.InvocationResp
	{
		client.Mutex.Lock()
		defer client.Mutex.Unlock()
		// Marshal the invocation directly in the args pipe
		err = client.ArgsEncoder.Encode(invocation)
		if err != nil {
			fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Error encoding invocation for server {{$service}}: %v\n", err)
			err = errors.New("error encoding invocation for server {{$service}}: " + err.Error())
			return
		}


		err = client.ResultDecoder.Decode(&response)
		if err != nil {
			fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Error decoding response from server {{$service}} for method {{Signature $f}}: %v\n", err)
			err = errors.New("error decoding response from server {{$service}}: " + err.Error())
			return
		}
	}

	if response.Err != "" {
		fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Server {{$service}} returned an error: %s\n", response.Err)
		err = errors.New(response.Err)
		return
	}

	// Read the response from the result pipe
	results := struct {
		{{range $i, $ret := $f.Returns}}
		Ret{{$i}} {{NameOf $ret.Type}}
		{{end}}
	}{}

	err = json.Unmarshal(response.Resp, &results)
	if err != nil {
		fmt.Printf("[[[[NAMED PIPES CLIENT]]]] Error unmarshalling response from server {{$service}}: error = %v, results = %+v\n", err, response.Resp)
		return
	}

	// Extract the return values from the result and return them from this function
	{{range $i, $_ := $f.Returns}}
	ret{{$i}} = results.Ret{{$i}}
	{{end}}
	return
}
{{end}}
`
