package namedpipecodegen

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

/*
This function is used by the namedpipe plugin to generate the server-side namedpipe service.
*/
func GenerateServerHandler(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_NamedPipeServerHandler",
		Imports: gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "encoding/json", "os", "fmt", "time", "github.com/blueprint-uservices/blueprint/runtime/plugins/namedpipe")

	slog.Info(fmt.Sprintf("Generating %v/%v_NamedPipeServer.go", server.Package.PackageName, service.BaseName))
	outputFile := filepath.Join(server.Package.Path, service.BaseName+"_NamedPipeServer.go")
	return gogen.ExecuteTemplateToFile("NamedPipeServer", serverTemplate, server, outputFile)
}

/*
Arguments to the template code
*/
type serverArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string         // Name of the generated wrapper class
	Imports *gogen.Imports // Manages imports for us
}

var serverTemplate = `// Blueprint: Auto-generated by Named Pipe Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
}

/// CONSTRUCTOR

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}, serveraddress string) (*{{.Name}}, error) {
	s := &{{.Name}}{}
	s.Service = service
	return s, nil
}

/// EVENT LOOP AND HELPER GOROUTINES

func (handler *{{.Name}}) poller(pipeNameUniqueSuffix string, r *os.File, w *os.File) {
	jsonDecoder := json.NewDecoder(r)
	jsonEncoder := json.NewEncoder(w)

	sendErrorBack := func(msg string) {
		resp := namedpipe.InvocationResp{
			Err: msg,
		}
		err := jsonEncoder.Encode(resp)
		if err != nil {
			fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] Error encoding error response for pipe %s: %v\n", pipeNameUniqueSuffix, err)
			return
		}
	}

	for {
		var req namedpipe.Invocation
		var resp namedpipe.InvocationResp

		err := jsonDecoder.Decode(&req)
		if err != nil {
			fmt.Printf("Error decoding args from client's %s args pipe: %v. Replying with error.\n", pipeNameUniqueSuffix, err)
			sendErrorBack(fmt.Sprintf("Error decoding request, err=%v", err))
			continue
		}

		switch req.Method {
			{{ range $_, $f := .Service.Methods }}
			case "{{$f.Name}}":
				handler.{{$f.Name}}(req, &resp)
			{{end}}
		default:
			resp.Err = fmt.Sprintf("Unknown method: %s", req.Method)
		}

		err = jsonEncoder.Encode(resp)
		if err != nil {
			fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] Error encoding response for method %s: %v\n", req.Method, err)
			sendErrorBack(fmt.Sprintf("Error encoding response, err=%v", err))
			continue
		}
	}
}

func (handler *{{.Name}}) newPipeHook() {
	// data structure to keep track of the existing pipes
	seenClients := make(map[string]struct{})

	// timer to poll periodically
	ticker := time.NewTicker(2 * time.Second)

	// periodically check for new pipes
	for range ticker.C {
		clients, err := namedpipe.GetClientsList("{{.Service.Name}}")
		if err != nil {
			fmt.Printf("Skipping newPipeHook tick because of an error while getting clients list: %v\n", err)
			continue
		}
		for _, client := range clients {
			if _, exists := seenClients[client]; !exists {
				seenClients[client] = struct{}{}
				fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] New client detected: %s\n", client)
				fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] Open args read pipe %s...\n", namedpipe.GetArgsPipeName("{{.Service.Name}}", client))
				r, rErr := namedpipe.OpenReadPipe(namedpipe.GetArgsPipeName("{{.Service.Name}}", client))
				fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] Open result write pipe %s...\n", namedpipe.GetArgsPipeName("{{.Service.Name}}", client))
				w, wErr := namedpipe.OpenWritePipe(namedpipe.GetResultPipeName("{{.Service.Name}}", client))
				if rErr != nil || wErr != nil {
					fmt.Printf("Error opening pipes for client %s: %v, %v\n", client, rErr, wErr)
					continue
				}
				fmt.Printf("[[[[NAMED PIPES SERVER {{.Service.Name}}]]]] Both pipes are setup for client %s!\n", client)
				go handler.poller(client, r, w)
			}
		}
	}
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *{{.Name}}) Run(ctx context.Context) error {
	var err error
	go func() {
		select {
		case <-ctx.Done():
			os.Exit(0)
		}
	}()

	tmpDirPath := namedpipe.GetTmpDir("{{.Service.Name}}")
	// cleanup of directory
	if err = os.RemoveAll(tmpDirPath); err != nil && !os.IsNotExist(err) {
		fmt.Printf("Error cleaning up directory %s: %v\n", tmpDirPath, err)
		return fmt.Errorf("Failed to cleanup directory %s: %v", tmpDirPath, err)
	}
	// recreate directory
	if err = os.MkdirAll(tmpDirPath, 0700); err != nil {
		fmt.Printf("Error making the directory %s: %v\n", tmpDirPath, err)
		return fmt.Errorf("Failed to create directory %s: %v", tmpDirPath, err)
	}
	// also schedule a cleanup at the end
	defer os.RemoveAll(tmpDirPath)

	// Spawn a goroutine that checks the /tmp/Blueprint{{.Service.Name}} folder for new pipes
	go handler.newPipeHook()

	for {
		select {
		case <-ctx.Done():
			fmt.Println("Context done, exiting server...")
			return nil
		default:
			// Keep the server running
			time.Sleep(1 * time.Second)
		}
	}
	return nil
}


{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}}
	(invocation namedpipe.Invocation, resp *namedpipe.InvocationResp) {

	var err error

	args := struct {
		{{range $_, $arg := $f.Arguments}}
		{{Title $arg.Name}} {{NameOf $arg.Type}}
		{{end}}
	}{}

	err = json.Unmarshal(invocation.Args, &args)
	if err != nil {
		resp.Err = "error unmarshalling args: " + err.Error()
		return
	}
	
	{{range $_, $arg := $f.Arguments}}
	{{$arg.Name}} := args.{{Title $arg.Name}}
	{{end}}

	// I see "cxt context.Context" as argument of many methods of blueprint applications, for example the dsb_hotel.
	// Also, all backend interfaces have a context.Context as first argument of each method.
	ctx := context.Background()
	// Here we are putting the context as first argument to the service handler
	{{RetVars $f "err"}} {{HasNewReturnVars $f}} handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
	if err != nil {
		resp.Err = "service returned error: " + err.Error()
		return
	}

	// Create struct for the return type of this specific method
	response := struct {
		{{range $i, $ret := $f.Returns}}
		Ret{{$i}} {{NameOf $ret.Type}}
		{{end}}
	}{}

	{{range $i, $arg := $f.Returns}}
	response.Ret{{$i}} = ret{{$i}}
	{{end}}

	resp.Resp, err = json.Marshal(response)
	if err != nil {
		resp.Err = "error marshalling result: " + err.Error()
	}
	return
}
{{end}}
`
